/* Generated By:JavaCC: Do not edit this line. SoyFileParserConstants.java */
package com.google.template.soy.soyparse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface SoyFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int AS = 11;
  /** RegularExpression Id. */
  int ALIAS_OPEN = 12;
  /** RegularExpression Id. */
  int CSSBASE = 13;
  /** RegularExpression Id. */
  int NAMESPACE_OPEN = 14;
  /** RegularExpression Id. */
  int AUTOESCAPE = 15;
  /** RegularExpression Id. */
  int REQUIRECSS = 16;
  /** RegularExpression Id. */
  int DELPACKAGE_OPEN = 17;
  /** RegularExpression Id. */
  int ATTRIBUTE_VALUE = 18;
  /** RegularExpression Id. */
  int WS = 19;
  /** RegularExpression Id. */
  int IDENT = 20;
  /** RegularExpression Id. */
  int DOTTED_IDENT = 21;
  /** RegularExpression Id. */
  int TEMPLATE_OPEN_SUFFIX = 22;
  /** RegularExpression Id. */
  int DELTEMPLATE_OPEN = 23;
  /** RegularExpression Id. */
  int TEMPLATE_OPEN = 24;
  /** RegularExpression Id. */
  int TEMPLATE_CONTENT = 26;
  /** RegularExpression Id. */
  int DELTEMPLATE_CONTENT = 27;
  /** RegularExpression Id. */
  int SOYDOC = 30;
  /** RegularExpression Id. */
  int UNEXPECTED_TOKEN = 31;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTILINE_COMMENT = 1;
  /** Lexical state. */
  int IN_DELTEMPLATE = 2;
  /** Lexical state. */
  int IN_TEMPLATE = 3;
  /** Lexical state. */
  int IN_SOYDOC = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"}\"",
    "\"=\"",
    "\"as\"",
    "\"{alias\"",
    "\"cssbase\"",
    "\"{namespace\"",
    "\"autoescape\"",
    "\"requirecss\"",
    "\"{delpackage\"",
    "<ATTRIBUTE_VALUE>",
    "<WS>",
    "<IDENT>",
    "<DOTTED_IDENT>",
    "<TEMPLATE_OPEN_SUFFIX>",
    "<DELTEMPLATE_OPEN>",
    "<TEMPLATE_OPEN>",
    "<token of kind 25>",
    "\"{/template}\"",
    "\"{/deltemplate}\"",
    "\"/**\"",
    "<token of kind 29>",
    "\"*/\"",
    "<UNEXPECTED_TOKEN>",
  };

}
