/* Generated By:JavaCC: Do not edit this line. TypeParserConstants.java */
package com.google.template.soy.types.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TypeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LANGLE = 1;
  /** RegularExpression Id. */
  int RANGLE = 2;
  /** RegularExpression Id. */
  int LBRACKET = 3;
  /** RegularExpression Id. */
  int RBRACKET = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int VBAR = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int QMARK = 9;
  /** RegularExpression Id. */
  int GENERIC_LIST = 10;
  /** RegularExpression Id. */
  int GENERIC_MAP = 11;
  /** RegularExpression Id. */
  int IDENT = 12;
  /** RegularExpression Id. */
  int WS = 13;
  /** RegularExpression Id. */
  int UNEXPECTED_TOKEN = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"|\"",
    "\":\"",
    "\".\"",
    "\"?\"",
    "\"list\"",
    "\"map\"",
    "<IDENT>",
    "<WS>",
    "<UNEXPECTED_TOKEN>",
  };

}
